# -*- coding: utf-8 -*-
"""Matrices

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hEclwSYV8GtT5UFvhWA4vlF9MrA-U1gQ
"""

from vectors import Vectors

class Matrices:
  def __init__(self, matrix : list[list[float]]):

    self.matrix = matrix

    if not matrix:
      raise ValueError("Matrix should at least have a single value")

    col_len = len(matrix[0])
    for row in matrix:
      if len(row) != col_len:
        raise ValueError("all rows must have the same lenght")

    self.rows = []
    for row in matrix:
      self.rows.append(Vectors(row))


    self.num_row = len(self.rows)
    self.num_cols = self.rows[0].size
    self.shape_attr = (self.num_row, self.num_cols)

  def __repr__ (self):
    rep = ""
    for i in self.rows:
      rep += f"{str(i)} \n"

    return rep

  def shape (self) -> tuple:
    return self.shape_attr

  def __len__ (self):
    return self.num_row

  def __getitem__(self, place):
    return self.matrix[place]

  def __add__(self,other):

    if not isinstance(other, self.__class__):
      raise ValueError("input should be a matrix")

    matx = [[0 for _ in range(self.num_cols)] for _ in range(self.num_row)]

    if self.shape_attr != other.shape_attr:
      raise ValueError("matrices should match in shape")

    else:
      for i in range(self.num_row):
        for j in range(self.num_cols):
          matx[i][j] = self.matrix[i][j] + other.matrix[i][j]

    return Matrices(matx)

  def __sub__(self, other):
    if not isinstance(other, self.__class__):
      raise ValueError("input should be a matrix")

    matx = [[0 for _ in range(self.num_cols)] for _ in range(self.num_row)]

    if self.shape_attr != other.shape_attr:
      raise ValueError("matrices should match in shape")

    else:
      for i in range(self.num_row):
        for j in range(self.num_cols):
          matx[i][j] = self.matrix[i][j] - other.matrix[i][j]

    return Matrices(matx)

  def extract_columns(self):
      columns = []

      for i in range(self.num_cols):
          col = []
          for j in range(self.num_row):
              col.append(self.matrix[j][i])
          columns.append(Vectors(col))

      return columns

  def __mul__(self, other):
      if not isinstance(other, Matrices):
          raise ValueError("input should be a matrix")

      if self.num_cols != other.num_row:
          raise ValueError("number of columns of the left matrix must equal the number of rows of the right matrix")

      other_cols = other.extract_columns()

      result = []
      for i in range(self.num_row):
          row_vec = self.rows[i]
          new_row = []
          for col_vec in other_cols:
              new_row.append(row_vec.dot(col_vec))
          result.append(new_row)

      return Matrices(result)

  def transpose(self):
      columns = self.extract_columns()

      transposed = []
      for col_vec in columns:
          transposed.append(list(col_vec))

      return Matrices(transposed)

a = Matrices([[1,2,3],[1,2,3]])
b = a

c = qb * a