# -*- coding: utf-8 -*-
"""Vectors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tumuHZZMDmyD-kbPOGQtUen9QLJyeWiY
"""

class Vectors:
  def __init__(self, numbers: list[float]):
    """
    Constructore function for vector initilization
    Args:
      numbers (list[float]): list of numbers for vector

    Returns:
      None
    """

    #check if numbers are empty
    if not numbers:
      raise ValueError("Vectors must have at least one number")
    self.numbers = numbers
    #the size of the vector
    self.size = len(numbers)

  def __repr__(self) -> str:
    """
    vector printing function for when we use print(vector)
    Args:
      None

    Returns:
      str: string representation of the vector
    """
    return f"Vector({self.numbers})"

  def __str__(self) -> str:
    """
    vector printing function for when we use print(vector)
    Args:
      None

    Returns:
      str: string representation of the vector
    """
    return f"Vector({self.numbers})"

  def __len__(self) -> int:
    """
    vector length function
    Args:
      None

    Returns:
      int: length of the vector
    """
    return self.size

  def __iter__(self):
    """
    Iterator function for the vector
    Args:
      None

    Returns:
      iterator: Iterator object
    """
    for iterator in self.numbers:
      yield iterator

  def __getitem__(self, index: int):
    """
    A function to return the index of the vector
    Args:
      index (int): index of the vector

    Returns:
      float: value of the index
    """
    if index <= 0 and index >= self.size:
      raise IndexError("index out of range")

    return self.numbers[index]

  def __setitem__(self, index: int, value: float):
    """
    A function to set the index of the vector
    Args:
      index (int): index of the vector
      value (float): value to set the index to

    Returns:
      None
    """
    self.numbers[index] = value

  def __add__(self, other):
    """
    A function to add two vectors
    Args:
      other (list: float): Vector to add to the current vector

    Returns:
      Vector: Vector that is the sum of the current vector and the other vector
    """
    result = []

    #check if both are the same type (vectors)
    if isinstance(other, Vectors):

      #if not the same size return an error
      assert self.size == len(other) , "vectors are not the same size"

      #loop and add through the vectors
      for i in range(len(self.numbers)):
        result.append(self.numbers[i] + other[i])
      return Vectors(result)

    #if not the same type (float or integer)
    else:

      #check if the to add is either an int or a float
      if isinstance(other, (int, float)):
        #loop and add through the vector
        for i in range(len(self.numbers)):
          result.append(self.numbers[i] + other)
        return Vectors(result)
      else:
        #if not either an int or a float return an error
        raise TypeError("other must be a vector or a number")

  def __radd__(self, other):
    """
    A function to add two vectors, right side addition
    Args:
      other (list: float): Vector to add to the current vector

    Returns:
      Vector: Vector that is the sum of the current vector and the other vector
    """
    return self.__add__(other)

  def __sub__(self, other):
    """
    A function to subtract two vectors
    Args:
      other (list: float): Vector to subtract from the current vector

    Returns:
      Vector: Vector that is the difference of the current vector and the other vector
    """
    result = []

    #check if both are the same type (vectors)
    if isinstance(other, Vectors):

      #if not the same size return an error
      assert self.size == len(other) , "vectors are not the same size"

      #loop and add through the vectors
      for i in range(len(self.numbers)):
        result.append(self.numbers[i] - other[i])
      return Vectors(result)

    #if not the same type (float or integer)
    else:

      #check if the to add is either an int or a float
      if isinstance(other, (int, float)):
        #loop and add through the vector
        for i in range(len(self.numbers)):
          result.append(self.numbers[i] - other)
        return Vectors(result)
      else:
        #if not either an int or a float return an error
        raise TypeError("other must be a vector or a number")

  def __rsub__(self, other):
    """
    A function to subtract two vectors, right side subtraction
    Args:
      other (list: float): Vector to subtract from the current vector

    Returns:
      Vector: Vector that is the difference of the current vector and the other vector
    """

    result = []

    #check if both are the same type (vectors)
    if isinstance(other, Vectors):

      #if not the same size return an error
      assert self.size == len(other) , "vectors are not the same size"

      #loop and add through the vectors
      for i in range(len(self.numbers)):
        result.append(other[i] - self.numbers[i])
      return Vectors(result)

    #if not the same type (float or integer)
    else:

      #check if the to add is either an int or a float
      if isinstance(other, (int, float)):
        #loop and add through the vector
        for i in range(len(self.numbers)):
          result.append(other - self.numbers[i])
        return Vectors(result)
      else:
        #if not either an int or a float return an error
        raise TypeError("instance must be a vector or a number")

  def __mul__(self, other):
    """
    A function to multiply two vectors
    Args:
      other (list: float): Vector to multiply to the current vector

    Returns:
      Vector: Vector that is the product of the current vector and the other vector
    """
    result = []

    #check if both are the same type (vectors)
    if isinstance(other, Vectors):

      assert self.size == len(other), "vectors are not the same size"

      for i in range(self.size):
        result.append(self.numbers[i] * other[i])
      return Vectors(result)

    else:
      if isinstance(other, (int,float)):
        for i in range(self.size):
          result.append(self.numbers[i] * other)
        return Vectors(result)

      else:
        raise TypeError("instance must be a vector or a number")

  def __rmul__ (self, other):
    return self.__mul__(other)


  def dot(self, other):
    """
    A function to perform dot product on two vectors
    Args:
      other (list: float): The vector to perform multiplication on

    Returns
      result (float): the outcome of the dot product
    """

    if isinstance(other, (Vectors,list)):
      result = 0
      assert self.size == len(other), "vectors are not the same size"

      for i in range(self.size):
        result = self.numbers[i] * other[i] + result

      return result
    else:
      raise TypeError("Dot product requires another vector, if needes scalar multiplication use *")

  def __truediv__(self, other):
    """
    A function to perform divison on two vectors
    Args:
      other (list: float): The vector to perform division on

    Returns
      result (float): the outcome of the division
    """

    result = []

    if isinstance(other, (Vectors, list)):
      if any(element == 0 for element in other):
        raise ZeroDivisionError("division by zero")

      assert self.size == len(other), "vectors are not the same size"

      for i in range(self.size):
        result.append(self.numbers[i] / other[i])
      return Vectors(result)

    else:
      if isinstance(other, (int, float)):
        if other == 0:
          raise ZeroDivisionError("division by zero")

        for i in range(self.size):
          result.append(self.numbers[i] / other)
        return Vectors(result)
      else:
        raise TypeError("instance must be a vector or a number")

  def __pow__(self, other):
    """
    A function to perform power operation on two vectors
    Args:
      other (list: float): The vector to perform power on

    Returns
      result (float): the outcome of the power
    """
    result = []

    if isinstance(other , (Vectors,list)):
      assert self.size == len(other), "vectors are not the same size"
      for i in range(self.size):
        result.append(self.numbers[i] ** other[i])

      return Vectors(result)

    else:
      if isinstance(other , (int, float)):
        for i in range(self.size):
          result.append(self.numbers[i] ** other)

        return Vectors(result)

  def __rpow__(self, other):
    """
    A function to perform power operation on two vectors, right side operation
    Args:
      other (list: float): The vector to perform power on

    Returns
      result (float): the outcome of the power
    """
    result = []

    if isinstance(other , (Vectors,list)):
      assert self.size == len(other), "vectors are not the same size"
      for i in range(self.size):
        result.append(other[i] ** self.numbers[i])

      return Vectors(result)

    else:
      if isinstance(other , (int, float)):
        for i in range(self.size):
          result.append(other ** self.numbers[i])

        return Vectors(result)

  def shape(self) -> tuple:
    """
    returns the shape of the vector
    Args:
     None

    Returns:
      tuple: the size of the vector
    """
    return [self.size,1]

  def sum(self) -> float:
    """
    Calculates the sum of all of the vectors elements
    Args:
     None

    Returns:
      sum (float): the sum of all the elements in the vector
    """

    sum = 0
    for i in range(self.size):
      sum = self.numbers[i] + sum

    return sum